# Generated by Django 4.1.2 on 2023-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование на русском')),
                ('title_en', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование на английском')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('length', models.CharField(blank=True, max_length=250, null=True, verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
