# Generated by Django 4.1.2 on 2023-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpoisk_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='position_in_top',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в ТОПе'),
        ),
    ]
