# Generated by Django 4.1.2 on 2023-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpoisk_parser', '0002_movie_position_in_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
